### ISSUE TITLE
Active Record Location is referencing Gem files instead of project code

### ISSUE THREAD

**Issue by klueless-io** [dejan/rails_panel#171]
Active Record Location is referencing Gem files instead of project code

![image](https://user-images.githubusercontent.com/2956762/68722878-ffd7e500-060a-11ea-9eb8-bec118339197.png)

**Comment by 0xdevalias** [comment]
It looks like the following is responsible for this logic:

- https://github.com/dejan/rails_panel/blob/master/meta_request/lib/meta_request/utils.rb#L8

`caller` contains an array of 'stacktrace' paths, eg:

```ruby
=> ["/Users/REDACTED/dev/REDACTED/vendor/bundle/ruby/2.4.0/gems/meta_request-0.7.2/lib/meta_request/app_notifications.rb:81:in `block in subscribe'",
 "/Users/REDACTED/dev/REDACTED/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:129:in `finish'",
 "/Users/REDACTED/dev/REDACTED/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:48:in `block in finish'",

..snip..
```

I'm not really sure of the intent of this code and how it flows through to other areas within the application to know if/how to modify it though.

The following helper could also potentially be changed to shorten the rails root 'prefix' from these paths, to make them a bit shorter

- https://github.com/dejan/rails_panel/blob/master/meta_request/lib/meta_request/utils.rb#L20-L26

**Comment by 0xdevalias** [comment]
By changing [this line](https://github.com/dejan/rails_panel/blob/master/meta_request/lib/meta_request/utils.rb#L8) to the following, you can skip past all the bundled vendor dependencies and likely land in the most relevant 'last point of call' within your application code itself:

```ruby
caller.detect { |c| c.start_with?(MetaRequest.rails_root) && !c.include?(File.join(MetaRequest.rails_root, 'vendor')) }
```

**Comment by bingxie** [comment]
Could we have a new version to fix this?
