### ISSUE TITLE
SystemStackError: stack level too deep with Rails 6.1

### ISSUE THREAD

**Issue by javierav** [dejan/rails_panel#178]
This gem is failing in Rails 6.1 with a `SystemStackError: stack level too deep` error.

See rails/rails#40698

**Comment by jkeen** [comment]
yep, same for me

**Comment by mikelieser** [comment]
same here. `rails new demoapp` (rails 6.1) and use the gem in dev group to reproduce it.

**Comment by meliborn** [comment]
Any news?

**Comment by istvan-ujjmeszaros** [comment]
@dejan is there any chance that you merge the [PR that fixes this issue](https://github.com/dejan/rails_panel/pull/177)?

**Comment by bartimez** [comment]
This is blocking our upgrade and we'll have to dump the gem until it's fixed.  Any news?

**Comment by viktorianer** [comment]
I just created a new app and added `meta_request` to this project. Doesn't work with rails 6.1.3 and Ruby 3.0.0.

Here's the stack trace:

```
SystemStackError (stack level too deep):

activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:175:in `dup'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:174:in `each'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:174:in `as_json'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:174:in `each'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:174:in `as_json'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:58:in `as_json'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:174:in `each'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:174:in `as_json'
activesupport (6.1.3.1) lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
...

meta_request (0.7.2) lib/meta_request/event.rb:46:in `block in json_encodable'
meta_request (0.7.2) lib/meta_request/event.rb:66:in `block in transform_hash'
meta_request (0.7.2) lib/meta_request/event.rb:60:in `each'
meta_request (0.7.2) lib/meta_request/event.rb:60:in `inject'
meta_request (0.7.2) lib/meta_request/event.rb:60:in `transform_hash'
meta_request (0.7.2) lib/meta_request/event.rb:38:in `json_encodable'
meta_request (0.7.2) lib/meta_request/event.rb:15:in `initialize'
meta_request (0.7.2) lib/meta_request/app_notifications.rb:69:in `new'
meta_request (0.7.2) lib/meta_request/app_notifications.rb:69:in `block in subscribe'
meta_request (0.7.2) lib/meta_request/app_notifications.rb:81:in `block in subscribe'
activesupport (6.1.3.1) lib/active_support/notifications/fanout.rb:186:in `finish'
...
actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
meta_request (0.7.2) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
meta_request (0.7.2) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
...
rack-contrib (2.3.0) lib/rack/contrib/response_headers.rb:19:in `call'
meta_request (0.7.2) lib/meta_request/middlewares/headers.rb:16:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
...
rack-mini-profiler (2.3.2) lib/mini_profiler/profiler.rb:384:in `call'
webpacker (5.3.0) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
puma (5.2.2) lib/puma/configuration.rb:248:in `call'
puma (5.2.2) lib/puma/request.rb:76:in `block in handle_request'
puma (5.2.2) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
puma (5.2.2) lib/puma/request.rb:75:in `handle_request'
puma (5.2.2) lib/puma/server.rb:431:in `process_client'
puma (5.2.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

**Comment by younthu** [comment]
Same here with rails 6.1.3

**Comment by Viktor-Ivliev** [comment]
I also confirmed an error on rails 6.1.3

**Comment by coderberry** [comment]
Same

```
About your application's environment
Rails version             6.1.3.1
Ruby version              ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin20]
RubyGems version          3.0.3
Rack version              2.2.3
JavaScript Runtime        mini_racer (V8)
```

**Comment by maurosbu** [comment]
Same here

```
About your application's environment
Rails version             6.1.4
Ruby version              ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
RubyGems version          3.2.19
Rack version              2.2.3
JavaScript Runtime        mini_racer (V8)
```

**Comment by maurosbu** [comment]
Installing from github seems to solve the problem. 
Put the following in the Gemfile:

`gem 'meta_request', github: 'dejan/rails_panel', branch: 'master', glob: 'meta_request/meta_request.gemspec'`

**Comment by lachances** [comment]
> Installing from github seems to solve the problem.
> Put the following in the Gemfile:
> 
> `gem 'meta_request', github: 'dejan/rails_panel', branch: 'master', glob: 'meta_request/meta_request.gemspec'`

This has solved it for me 👍

**Comment by maurosbu** [comment]
@dejan is it possible to release a new version of the gem? Thx

**Comment by dejan** [comment]
New version of the gem (meta-requst-0.7.3) is released. Thanks everyone.

**Comment by ahmedsayedabdelsalam** [comment]
same issue on 0.7.3

**Comment by matedemorphy** [comment]
doesn't works for rails 7:

Could not find compatible versions

```
Could not find compatible versions

Because rails >= 7.1.1, < 7.1.2 depends on railties = 7.1.1
  and rails >= 7.1.0, < 7.1.1 depends on railties = 7.1.0,
  rails >= 7.1.0, < 7.1.2 requires railties = 7.1.0 OR = 7.1.1.
And because rails >= 7.1.2 depends on railties = 7.1.2
  and meta_request >= 0.7.4 depends on railties >= 3.0.0, < 7.1,
  meta_request >= 0.7.4 is incompatible with rails >= 7.1.0.
So, because Gemfile depends on rails ~> 7.1.0
  and Gemfile depends on meta_request ~> 0.7.4,
  version solving has failed
```

**Comment by panaak** [comment]
works with rails 7.0.8.4
does not work with 7.1.3.4
