### ISSUE TITLE
Rails 7.2 compatibility issue

### ISSUE THREAD

**Issue by pnpk** [dejan/rails_panel#206]
Thank you for great work.

After updating from Rails version 7.1.4 to 7.2.1, a [SystemStackError: stack level too deep (SystemStackError)] occurs during updates using Active Record.
I would appreciate any advice on workarounds for this issue.

**Comment by jamiecobbett** [comment]
I'm experiencing this too, here's my stacktrace:

```
[activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:167:in `map'](http://localhost:3001/users/sign_in#)
[activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:167:in `as_json'](http://localhost:3001/users/sign_in#)
[activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:188:in `block in as_json'](http://localhost:3001/users/sign_in#)
[activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:187:in `each'](http://localhost:3001/users/sign_in#)
[activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:187:in `as_json'](http://localhost:3001/users/sign_in#)

[SNIP]

activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:188:in `block in as_json'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:187:in `each'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:187:in `as_json'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:63:in `as_json'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:188:in `block in as_json'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:187:in `each'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:187:in `as_json'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:63:in `as_json'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:188:in `block in as_json'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:187:in `each'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:187:in `as_json'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:63:in `as_json'
activesupport (7.2.1.1) lib/active_support/json/encoding.rb:39:in `encode'
activesupport (7.2.1.1) lib/active_support/json/encoding.rb:23:in `encode'
activesupport (7.2.1.1) lib/active_support/core_ext/object/json.rb:42:in `to_json'
meta_request (0.8.3) lib/meta_request/event.rb:50:in `block in json_encodable'
meta_request (0.8.3) lib/meta_request/event.rb:86:in `block in transform_hash'
meta_request (0.8.3) lib/meta_request/event.rb:80:in `each'
meta_request (0.8.3) lib/meta_request/event.rb:80:in `each_with_object'
meta_request (0.8.3) lib/meta_request/event.rb:80:in `transform_hash'
meta_request (0.8.3) lib/meta_request/event.rb:42:in `json_encodable'
meta_request (0.8.3) lib/meta_request/event.rb:18:in `initialize'
meta_request (0.8.3) lib/meta_request/app_notifications.rb:47:in `new'
meta_request (0.8.3) lib/meta_request/app_notifications.rb:47:in `block in <class:AppNotifications>'
meta_request (0.8.3) lib/meta_request/app_notifications.rb:82:in `block in subscribe'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:134:in `block in finish'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:25:in `block in iterate_guarding_exceptions'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:24:in `each'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:24:in `iterate_guarding_exceptions'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:122:in `each'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:133:in `finish'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:259:in `block in finish_with_values'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:25:in `block in iterate_guarding_exceptions'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:24:in `each'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:24:in `iterate_guarding_exceptions'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:258:in `finish_with_values'
activesupport (7.2.1.1) lib/active_support/notifications/fanout.rb:251:in `finish'
activesupport (7.2.1.1) lib/active_support/notifications/instrumenter.rb:64:in `ensure in instrument'
activesupport (7.2.1.1) lib/active_support/notifications/instrumenter.rb:64:in `instrument'
activerecord (7.2.1.1) lib/active_record/connection_adapters/abstract_adapter.rb:1119:in `log'
activerecord (7.2.1.1) lib/active_record/connection_adapters/postgresql_adapter.rb:892:in `exec_no_cache'
activerecord (7.2.1.1) lib/active_record/connection_adapters/postgresql_adapter.rb:872:in `execute_and_clear'
activerecord (7.2.1.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:79:in `exec_delete'
activerecord (7.2.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:208:in `update'
activerecord (7.2.1.1) lib/active_record/connection_adapters/abstract/query_cache.rb:27:in `update'
activerecord (7.2.1.1) lib/active_record/persistence.rb:280:in `block in _update_record'
activerecord (7.2.1.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:389:in `with_connection'
activerecord (7.2.1.1) lib/active_record/connection_handling.rb:296:in `with_connection'
activerecord (7.2.1.1) lib/active_record/persistence.rb:279:in `_update_record'
activerecord (7.2.1.1) lib/active_record/persistence.rb:887:in `_update_row'
activerecord (7.2.1.1) lib/active_record/locking/optimistic.rb:93:in `_update_row'
activerecord (7.2.1.1) lib/active_record/persistence.rb:909:in `_update_record'
activerecord (7.2.1.1) lib/active_record/attribute_methods/dirty.rb:234:in `_update_record'
activerecord (7.2.1.1) lib/active_record/callbacks.rb:449:in `block (2 levels) in _update_record'
activerecord (7.2.1.1) lib/active_record/timestamp.rb:140:in `record_update_timestamps'
activerecord (7.2.1.1) lib/active_record/callbacks.rb:449:in `block in _update_record'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:110:in `run_callbacks'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:913:in `_run_update_callbacks'
activerecord (7.2.1.1) lib/active_record/callbacks.rb:449:in `_update_record'
activerecord (7.2.1.1) lib/active_record/timestamp.rb:122:in `_update_record'
activerecord (7.2.1.1) lib/active_record/persistence.rb:896:in `create_or_update'
activerecord (7.2.1.1) lib/active_record/callbacks.rb:441:in `block in create_or_update'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activerecord (7.2.1.1) lib/active_record/autosave_association.rb:362:in `around_save_collection_association'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:141:in `run_callbacks'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:913:in `_run_save_callbacks'
activerecord (7.2.1.1) lib/active_record/callbacks.rb:441:in `create_or_update'
activerecord (7.2.1.1) lib/active_record/timestamp.rb:127:in `create_or_update'
activerecord (7.2.1.1) lib/active_record/persistence.rb:393:in `save'
activerecord (7.2.1.1) lib/active_record/validations.rb:48:in `save'
activerecord (7.2.1.1) lib/active_record/transactions.rb:362:in `block in save'
activerecord (7.2.1.1) lib/active_record/transactions.rb:418:in `block (2 levels) in with_transaction_returning_status'
activerecord (7.2.1.1) lib/active_record/connection_adapters/abstract/transaction.rb:616:in `block in within_new_transaction'
activesupport (7.2.1.1) lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
activerecord (7.2.1.1) lib/active_record/connection_adapters/abstract/transaction.rb:613:in `within_new_transaction'
activerecord (7.2.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:361:in `transaction'
activerecord (7.2.1.1) lib/active_record/transactions.rb:414:in `block in with_transaction_returning_status'
activerecord (7.2.1.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:395:in `with_connection'
activerecord (7.2.1.1) lib/active_record/connection_handling.rb:296:in `with_connection'
activerecord (7.2.1.1) lib/active_record/transactions.rb:410:in `with_transaction_returning_status'
activerecord (7.2.1.1) lib/active_record/transactions.rb:362:in `save'
activerecord (7.2.1.1) lib/active_record/suppressor.rb:52:in `save'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/active_record_prepend.rb:30:in `block in save'
newrelic_rpm (9.14.0) lib/new_relic/agent/transaction.rb:884:in `with_database_metric_name'
newrelic_rpm (9.14.0) lib/new_relic/agent.rb:975:in `with_database_metric_name'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/active_record_prepend.rb:29:in `save'
devise (4.9.4) lib/devise/models/trackable.rb:40:in `update_tracked_fields!'
devise (4.9.4) lib/devise/hooks/trackable.rb:9:in `block in <main>'
warden (1.2.9) lib/warden/hooks.rb:15:in `block in _run_callbacks'
warden (1.2.9) lib/warden/hooks.rb:10:in `each'
warden (1.2.9) lib/warden/hooks.rb:10:in `_run_callbacks'
warden (1.2.9) lib/warden/manager.rb:52:in `_run_callbacks'
warden (1.2.9) lib/warden/proxy.rb:191:in `set_user'
warden (1.2.9) lib/warden/proxy.rb:339:in `_perform_authentication'
warden (1.2.9) lib/warden/proxy.rb:110:in `authenticate'
app/controllers/users/sessions_controller.rb:66:in `assign_resource'
app/controllers/users/sessions_controller.rb:28:in `create'
actionpack (7.2.1.1) lib/action_controller/metal/basic_implicit_render.rb:8:in `send_action'
actionpack (7.2.1.1) lib/abstract_controller/base.rb:226:in `process_action'
actionpack (7.2.1.1) lib/action_controller/metal/rendering.rb:193:in `process_action'
actionpack (7.2.1.1) lib/abstract_controller/callbacks.rb:261:in `block in process_action'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
i18n (1.14.6) lib/i18n.rb:353:in `with_locale'
app/controllers/concerns/localisation.rb:14:in `switch_locale'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
turbo-rails (2.0.10) lib/turbo-rails.rb:24:in `with_request_id'
turbo-rails (2.0.10) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
sentry-rails (5.21.0) lib/sentry/rails/controller_transaction.rb:32:in `block in sentry_around_action'
sentry-ruby (5.21.0) lib/sentry/hub.rb:108:in `with_child_span'
sentry-ruby (5.21.0) lib/sentry-ruby.rb:499:in `with_child_span'
sentry-rails (5.21.0) lib/sentry/rails/controller_transaction.rb:18:in `sentry_around_action'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:141:in `run_callbacks'
actionpack (7.2.1.1) lib/abstract_controller/callbacks.rb:260:in `process_action'
actionpack (7.2.1.1) lib/action_controller/metal/rescue.rb:27:in `process_action'
actionpack (7.2.1.1) lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'
activesupport (7.2.1.1) lib/active_support/notifications.rb:210:in `block in instrument'
activesupport (7.2.1.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.2.1.1) lib/active_support/notifications.rb:210:in `instrument'
actionpack (7.2.1.1) lib/action_controller/metal/instrumentation.rb:76:in `process_action'
actionpack (7.2.1.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.2.1.1) lib/active_record/railties/controller_runtime.rb:39:in `process_action'
actionpack (7.2.1.1) lib/abstract_controller/base.rb:163:in `process'
actionview (7.2.1.1) lib/action_view/rendering.rb:40:in `process'
actionpack (7.2.1.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (7.2.1.1) lib/action_controller/metal.rb:335:in `dispatch'
actionpack (7.2.1.1) lib/action_dispatch/routing/route_set.rb:67:in `dispatch'
actionpack (7.2.1.1) lib/action_dispatch/routing/route_set.rb:50:in `serve'
actionpack (7.2.1.1) lib/action_dispatch/routing/mapper.rb:32:in `block in <class:Constraints>'
actionpack (7.2.1.1) lib/action_dispatch/routing/mapper.rb:62:in `serve'
actionpack (7.2.1.1) lib/action_dispatch/journey/router.rb:53:in `block in serve'
actionpack (7.2.1.1) lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
actionpack (7.2.1.1) lib/action_dispatch/journey/router.rb:126:in `each'
actionpack (7.2.1.1) lib/action_dispatch/journey/router.rb:126:in `find_routes'
actionpack (7.2.1.1) lib/action_dispatch/journey/router.rb:34:in `serve'
actionpack (7.2.1.1) lib/action_dispatch/routing/route_set.rb:896:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
meta_request (0.8.3) lib/meta_request/middlewares/app_request_handler.rb:15:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
meta_request (0.8.3) lib/meta_request/middlewares/meta_request_handler.rb:15:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (9.14.0) lib/new_relic/rack/browser_monitoring.rb:38:in `traced_call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (3.1.8) lib/rack/tempfile_reaper.rb:20:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (3.1.8) lib/rack/etag.rb:29:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (3.1.8) lib/rack/conditional_get.rb:43:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (3.1.8) lib/rack/head.rb:15:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/cookies.rb:704:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activerecord (7.2.1.1) lib/active_record/migration.rb:674:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
activesupport (7.2.1.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.2.1.1) lib/action_dispatch/middleware/callbacks.rb:30:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/executor.rb:16:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
sentry-rails (5.21.0) lib/sentry/rails/rescued_exception_interceptor.rb:14:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-contrib (2.5.0) lib/rack/contrib/response_headers.rb:23:in `call'
meta_request (0.8.3) lib/meta_request/middlewares/headers.rb:18:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
sentry-ruby (5.21.0) lib/sentry/rack/capture_exceptions.rb:30:in `block (2 levels) in call'
sentry-ruby (5.21.0) lib/sentry/hub.rb:265:in `with_session_tracking'
sentry-ruby (5.21.0) lib/sentry-ruby.rb:412:in `with_session_tracking'
sentry-ruby (5.21.0) lib/sentry/rack/capture_exceptions.rb:21:in `block in call'
sentry-ruby (5.21.0) lib/sentry/hub.rb:59:in `with_scope'
sentry-ruby (5.21.0) lib/sentry-ruby.rb:392:in `with_scope'
sentry-ruby (5.21.0) lib/sentry/rack/capture_exceptions.rb:20:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (7.2.1.1) lib/rails/rack/logger.rb:41:in `call_app'
railties (7.2.1.1) lib/rails/rack/logger.rb:29:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
request_store (1.7.0) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/request_id.rb:33:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (3.1.8) lib/rack/method_override.rb:28:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (3.1.8) lib/rack/runtime.rb:24:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activesupport (7.2.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.2.1.1) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/executor.rb:16:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/static.rb:27:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (3.1.8) lib/rack/sendfile.rb:114:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (7.2.1.1) lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-mini-profiler (3.3.1) lib/mini_profiler.rb:334:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (7.2.1.1) lib/rails/engine.rb:535:in `call'
newrelic_rpm (9.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
puma (6.4.3) lib/puma/configuration.rb:272:in `call'
puma (6.4.3) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.3) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.3) lib/puma/request.rb:99:in `handle_request'
puma (6.4.3) lib/puma/server.rb:464:in `process_client'
puma (6.4.3) lib/puma/server.rb:245:in `block in run'
puma (6.4.3) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
newrelic_rpm (9.14.0) lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
newrelic_rpm (9.14.0) lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
newrelic_rpm (9.14.0) lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'
```

**Comment by jamiecobbett** [comment]
Seems to have the same symptom as this issue from 2015: https://github.com/dejan/rails_panel/issues/88 which was still present in 2022

**Comment by princekumarg12** [comment]
i have face same issue here

home/prince/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': stack level too deep (SystemStackError)
/home/prince/.rvm/gems/ruby-3.3.5/gems/activesupport-7.2.2/lib/active_support/core_ext/object/instance_variables.rb:15:in `to_h': stack level too deep (SystemStackError)
	from /home/prince/.rvm/gems/ruby-3.3.5/gems/activesupport-7.2.2/lib/active_support/core_ext/object/instance_variables.rb:15:in `instance_values'
	from /home/prince/.rvm/gems/ruby-3.3.5/gems/activesupport-7.2.2/lib/active_support/core_ext/object/json.rb:63:in `as_json'


it's not supported on  rails 8.0.0 too
