### ISSUE TITLE
Error when saving geographical model with postgis-activerecord gem

### ISSUE THREAD

**Issue by waissbluth** [dejan/rails_panel#88]
This issue seems to belong here: https://github.com/rgeo/activerecord-postgis-adapter/issues/81

**Comment by keepcosmos** [comment]
+1

**Comment by snkashis** [comment]
Yes, I had to discontinue usage of rails panel as well. Noticed meta_request was involved in causing SystemStackErrors on certain requests.  This `map,as_json,block in as_json` cycle is repeated many many times...This code below is from a PUT affecting a geographic model.
```
activesupport (4.1.10) lib/active_support/core_ext/object/json.rb:50:in `as_json'
activesupport (4.1.10) lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
activesupport (4.1.10) lib/active_support/core_ext/object/json.rb:140:in `map'
activesupport (4.1.10) lib/active_support/core_ext/object/json.rb:140:in `as_json'
activesupport (4.1.10) lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
activesupport (4.1.10) lib/active_support/core_ext/object/json.rb:140:in `map'
activesupport (4.1.10) lib/active_support/core_ext/object/json.rb:140:in `as_json'
activesupport (4.1.10) lib/active_support/json/encoding.rb:34:in `encode'
activesupport (4.1.10) lib/active_support/json/encoding.rb:21:in `encode'
activesupport (4.1.10) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
meta_request (0.3.4) lib/meta_request/event.rb:37:in `block in json_encodable'
meta_request (0.3.4) lib/meta_request/event.rb:57:in `call'
meta_request (0.3.4) lib/meta_request/event.rb:57:in `block in transform_hash'
meta_request (0.3.4) lib/meta_request/event.rb:51:in `each'
meta_request (0.3.4) lib/meta_request/event.rb:51:in `inject'
meta_request (0.3.4) lib/meta_request/event.rb:51:in `transform_hash'
meta_request (0.3.4) lib/meta_request/event.rb:35:in `json_encodable'
meta_request (0.3.4) lib/meta_request/event.rb:12:in `initialize'
meta_request (0.3.4) lib/meta_request/app_notifications.rb:16:in `new'
meta_request (0.3.4) lib/meta_request/app_notifications.rb:16:in `block in subscribe'
meta_request (0.3.4) lib/meta_request/app_notifications.rb:31:in `block in subscribe'
activesupport (4.1.10) lib/active_support/notifications/fanout.rb:122:in `call'
activesupport (4.1.10) lib/active_support/notifications/fanout.rb:122:in `finish'
activesupport (4.1.10) lib/active_support/notifications/fanout.rb:40:in `block in finish'
activesupport (4.1.10) lib/active_support/notifications/fanout.rb:40:in `each'
activesupport (4.1.10) lib/active_support/notifications/fanout.rb:40:in `finish'
activesupport (4.1.10) lib/active_support/notifications/instrumenter.rb:36:in `finish'
activesupport (4.1.10) lib/active_support/notifications/instrumenter.rb:25:in `instrument'
```

**Comment by TangMonk** [comment]
+1

**Comment by alexanderadam** [comment]
<details>
  <summary>This is still an issue in version 0.7.3 (click to expand stacktrace)</summary>


```
...
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `map'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:56:in `as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `block in as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `each'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `map'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:56:in `as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `block in as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `each'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `map'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:171:in `as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:56:in `as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:152:in `block in as_json'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:152:in `map'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:152:in `as_json'
/activesupport-5.2.6/lib/active_support/json/encoding.rb:35:in `encode'
/activesupport-5.2.6/lib/active_support/json/encoding.rb:22:in `encode'
/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:41:in `to_json'
/meta_request-0.7.3/lib/meta_request/event.rb:48:in `block in json_encodable'
/meta_request-0.7.3/lib/meta_request/event.rb:74:in `block in transform_hash'
/meta_request-0.7.3/lib/meta_request/event.rb:68:in `each'
/meta_request-0.7.3/lib/meta_request/event.rb:68:in `each_with_object'
/meta_request-0.7.3/lib/meta_request/event.rb:68:in `transform_hash'
/meta_request-0.7.3/lib/meta_request/event.rb:40:in `json_encodable'
/meta_request-0.7.3/lib/meta_request/event.rb:16:in `initialize'
/meta_request-0.7.3/lib/meta_request/app_notifications.rb:47:in `new'
/meta_request-0.7.3/lib/meta_request/app_notifications.rb:47:in `block in <class:AppNotifications>'
/meta_request-0.7.3/lib/meta_request/app_notifications.rb:82:in `block in subscribe'
/activesupport-5.2.6/lib/active_support/notifications/fanout.rb:129:in `finish'
/activesupport-5.2.6/lib/active_support/notifications/fanout.rb:48:in `block in finish'
/activesupport-5.2.6/lib/active_support/notifications/fanout.rb:48:in `each'
/activesupport-5.2.6/lib/active_support/notifications/fanout.rb:48:in `finish'
/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:44:in `finish_with_state'
/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:29:in `instrument'
/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_and_clear'
/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:94:in `exec_delete'
/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:170:in `update'
/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `update'
/activerecord-5.2.6/lib/active_record/persistence.rb:197:in `_update_record'
/activerecord-5.2.6/lib/active_record/locking/optimistic.rb:89:in `_update_row'
/activerecord-5.2.6/lib/active_record/persistence.rb:719:in `_update_record'
/activerecord-5.2.6/lib/active_record/attribute_methods/dirty.rb:134:in `_update_record'
/activerecord-5.2.6/lib/active_record/callbacks.rb:350:in `block in _update_record'
/activesupport-5.2.6/lib/active_support/callbacks.rb:132:in `run_callbacks'
/activesupport-5.2.6/lib/active_support/callbacks.rb:816:in `_run_update_callbacks'
/activerecord-5.2.6/lib/active_record/callbacks.rb:350:in `_update_record'
/activerecord-5.2.6/lib/active_record/timestamp.rb:114:in `_update_record'
/activerecord-5.2.6/lib/active_record/persistence.rb:705:in `create_or_update'
/activerecord-5.2.6/lib/active_record/callbacks.rb:342:in `block in create_or_update'
/activesupport-5.2.6/lib/active_support/callbacks.rb:132:in `run_callbacks'
/activesupport-5.2.6/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/activerecord-5.2.6/lib/active_record/callbacks.rb:342:in `create_or_update'
/activerecord-5.2.6/lib/active_record/persistence.rb:275:in `save'
/activerecord-5.2.6/lib/active_record/validations.rb:46:in `save'
/activerecord-5.2.6/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
/activerecord-5.2.6/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/activerecord-5.2.6/lib/active_record/transactions.rb:212:in `transaction'
/activerecord-5.2.6/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/activerecord-5.2.6/lib/active_record/transactions.rb:310:in `block in save'
/activerecord-5.2.6/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/activerecord-5.2.6/lib/active_record/transactions.rb:309:in `save'
/activerecord-5.2.6/lib/active_record/suppressor.rb:44:in `save'
/activerecord-5.2.6/lib/active_record/persistence.rb:428:in `block in update'
/activerecord-5.2.6/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/activerecord-5.2.6/lib/active_record/transactions.rb:212:in `transaction'
/activerecord-5.2.6/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/activerecord-5.2.6/lib/active_record/persistence.rb:426:in `update'
```


</details>
